# 使用配置文件进行网关路由配置
spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://services-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
#            - AddResponseHeader=X-Response-ABC,123
#          metadata:
#            hello: world
          order: 0
        - id: product-route
          uri: lb://services-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}
          order: 1

        - id: bing-route
          uri: https://www.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
                matchTrailingSlash: true
            - name: Query
              args:
                param: q
                regexp: haha
            - Vip=user,zhengyitao
#            - name: Vip
#              args:
#                param: user
#                value: zhengyitao
          order: 2
      default-filters:
        - AddResponseHeader=X-Response-ABC,123