spring:
  profiles:
    active: prod
    include: feign
  application:
    name: services-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
# 导入 Nacos 远程配置文件
  config:
    import: nacos:services-order.properties

server:
  port: 8000

# 启用 OpenFeign Debug级 日志
logging:
  level:
    com.hureru.order.feign: debug
